version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "docker-compose exec db psql -U postgres -c 'CREATE DATABASE tele_bot;' & python manage.py migrate && python manage.py startbot"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - pg_db
    env_file:
      - docker.env


  # PostgreSQL database service
  pg_db:
    container_name: pg_db
    hostname: db
    image: postgres:latest
    environment:
      POSTGRES_DB: tele_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
